name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1
  audio_session: ^0.1.6+1
  just_audio: ^0.9.13
  flutter_tts: ^3.2.2
  rxdart: ^0.27.2
  audio_service: 0.18.4

  native_admob_flutter: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true